<a href="https://colab.research.google.com/github/SoniaCamila13/Clasificacion_correos_BERT_USFQ/blob/main/notebooks/01_preprocesamiento_y_anonimizacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En esta primera parte se anonimizarán los datos del dataset (aproximandamente el contenido de 30000 correos) y se escoger de manera aleatoria 10 000 de ellos para etiquetarlos manualmente.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving bases_unificadas.csv to bases_unificadas.csv

Se carga el csv del dataset para anonimizar los datos:

In [ ]:
import pandas as pd

df = pd.read_csv("bases_unificadas.csv", sep=';')
df.head()

,Asunto,Cuerpo,Remitente,Etiqueta
0,Retiro de materia,"Buenas tardes,\r\n\r\nMi nombre es Alejandro X...",Alejandro Xavier Crespo Jativa,NaN
1,Retiro de materia,"Buenas tardes,\r\nEspero que estén bien. Les e...",Ingrid Belén Gutiérrez Pazmiño,NaN
2,RE: Registro de Graduacion,"Estimado,\r\n\r\nQueria cambiarle en donde pus...",David Eduardo Chacón Yépez,NaN
3,Solicitud de certificados para trámite de visa,"Estimados,\r\n\r\nEspero que estén teniendo un...",Grace Saltos,NaN
4,Solicitud de certificados para trámite de visa,"Estimados,\r\n\r\nEspero que estén teniendo un...",Grace Saltos,NaN

In [ ]:
df.shape

(29046, 4)

Se anonimizan direcciones de correo, cédulas, teléfonos y nombres

In [ ]:
import re

def anonymize_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # emails
    text = re.sub(r'\S+@\S+', '[EMAIL]', text)

    # cédulas o números largos
    text = re.sub(r'\b\d{7,13}\b', '[ID]', text)

    # teléfonos
    text = re.sub(r'\b\d{9,10}\b', '[PHONE]', text)

    # nombres después de frases comunes
    text = re.sub(r'(mi nombre es\s+)([A-ZÁÉÍÓÚÑ][a-záéíóúñ]+\s[A-ZÁÉÍÓÚÑ][a-záéíóúñ]+)', r'\1[NOMBRE]', text, flags=re.IGNORECASE)

    text = re.sub(r'(soy\s+)([A-ZÁÉÍÓÚÑ][a-záéíóúñ]+\s[A-ZÁÉÍÓÚÑ][a-záéíóúñ]+)', r'\1[NOMBRE]', text, flags=re.IGNORECASE)

    return text

In [ ]:
df["Asunto"] = df["Asunto"].apply(anonymize_text)
df["Cuerpo"] = df["Cuerpo"].apply(anonymize_text)
df["Remitente"] = df["Remitente"].apply(anonymize_text)

In [ ]:
df.head()

,Asunto,Cuerpo,Remitente,Etiqueta
0,Retiro de materia,"Buenas tardes,\r\n\r\nMi nombre es [NOMBRE] Cr...",Alejandro Xavier Crespo Jativa,NaN
1,Retiro de materia,"Buenas tardes,\r\nEspero que estén bien. Les e...",Ingrid Belén Gutiérrez Pazmiño,NaN
2,RE: Registro de Graduacion,"Estimado,\r\n\r\nQueria cambiarle en donde pus...",David Eduardo Chacón Yépez,NaN
3,Solicitud de certificados para trámite de visa,"Estimados,\r\n\r\nEspero que estén teniendo un...",Grace Saltos,NaN
4,Solicitud de certificados para trámite de visa,"Estimados,\r\n\r\nEspero que estén teniendo un...",Grace Saltos,NaN

In [ ]:
df.to_csv("correos_anonimizados.csv", index=False)

Se descarga el archivo

In [ ]:
from google.colab import files
files.download("correos_anonimizados.csv")

Se escogen 10000 correos de manera aleatoria para etiquetarlos manualmente

In [ ]:
df_sample = df.sample(n=10000, random_state=42)

In [ ]:
df_sample.shape

(10000, 4)

Se guarda el archivo de los 10000 correos para etiquetar

In [ ]:
df_sample.to_csv("correos_para_etiquetar.csv", index=False)

In [ ]:
from google.colab import files
files.download("correos_para_etiquetar.csv")